/*******************************************************************************
* File Name: cyfitter_cfg.h
* 
* PSoC Creator  4.4
*
* Description:
* This file provides basic startup and mux configuration settings
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef CYFITTER_CFG_H
#define CYFITTER_CFG_H

#include "cytypes.h"

extern void cyfitter_cfg(void);

/* Analog Set/Unset methods */
extern void SetAnalogRoutingPumps(uint8 enabled);
extern void AMux_TIA_input_Set(uint8 channel);
extern void AMux_TIA_input_Unset(uint8 channel);
/* AMux_TIA_input__addrTable is an implementation detail of the AMux.
   Code that depends on it may be incompatible with other versions
   of PSoC Creator. */
extern uint8 CYXDATA * const CYCODE AMux_TIA_input__addrTable[3];
/* AMux_TIA_input__maskTable is an implementation detail of the AMux.
   Code that depends on it may be incompatible with other versions
   of PSoC Creator. */
extern const uint8 CYCODE AMux_TIA_input__maskTable[3];
extern void AMux_TIA_resistor_bypass_Set(uint8 channel);
extern void AMux_TIA_resistor_bypass_Unset(uint8 channel);
/* AMux_TIA_resistor_bypass__addrTable is an implementation detail of the AMux.
   Code that depends on it may be incompatible with other versions
   of PSoC Creator. */
extern uint8 CYXDATA * const CYCODE AMux_TIA_resistor_bypass__addrTable[2];
/* AMux_TIA_resistor_bypass__maskTable is an implementation detail of the AMux.
   Code that depends on it may be incompatible with other versions
   of PSoC Creator. */
extern const uint8 CYCODE AMux_TIA_resistor_bypass__maskTable[2];
extern void AMux_V_source_Set(uint8 channel);
extern void AMux_V_source_Unset(uint8 channel);
/* AMux_V_source__addrTable is an implementation detail of the AMux.
   Code that depends on it may be incompatible with other versions
   of PSoC Creator. */
extern uint8 CYXDATA * const CYCODE AMux_V_source__addrTable[2];
/* AMux_V_source__maskTable is an implementation detail of the AMux.
   Code that depends on it may be incompatible with other versions
   of PSoC Creator. */
extern const uint8 CYCODE AMux_V_source__maskTable[2];
extern void AMux_electrode_Set(uint8 channel);
extern void AMux_electrode_Unset(uint8 channel);
/* AMux_electrode__addrTable is an implementation detail of the AMux.
   Code that depends on it may be incompatible with other versions
   of PSoC Creator. */
extern uint8 CYXDATA * const CYCODE AMux_electrode__addrTable[2];
/* AMux_electrode__maskTable is an implementation detail of the AMux.
   Code that depends on it may be incompatible with other versions
   of PSoC Creator. */
extern const uint8 CYCODE AMux_electrode__maskTable[2];


#endif /* CYFITTER_CFG_H */

/*[]*/
